transaction_and_hash = ('IHWBOXGKKUZDSSMVJKXGEQDSNWREWQROJFWFPFIGHDSRHOZTDBYZPAQQDQCIASONKDWMULCHMYWKDLGPA' +
                        'MFVIPRIWOUWCAYGPWOCI9QKGQNDJVNGGWGQSLIFJGJOKIZPUAXPINEYYHCVSSBFQPPQLWXBCCSPWWHVER' +
                        'TDALI9UNPZGIY9DD9VEDIABNLAJZZJPXERSISFGGHOUAQCKUBOJPRCOVPVXJJOGGWBOAZLI9QH9B9NYLK' +
                        'XITTBH9MQMFZYZUZFKGC9VQKN9KA9XDQZMBABOT9ARLMIXQHWARWMB9UIDRYRC9SSKYEYUNX9SGDSNXTA' +
                        '9LDJOWZUVKBYYBPUGSMIONX9LFNOKYDVEMNCAGCOGNOTUNZKSPOUVPHLGIMQMQGIUPIBGLVERWWGMINIT' +
                        'AYVWLKMPVMZ9B9HNXAW9ZP9UWCRNQOLSPKMYZJVLRHQVNVFHFVIQFOY9UBYMRLLEKAGITQNJIZNFYDY9O' +
                        'PJYHFJHCRUTEWXZUQEHLUSYPHXIGL9YPRXIUTGCD9JUAJUZ9TX9XPTWCDO9ULRJ9DXENRFLWCSAZJDDFM' +
                        'FFHGQCQZGIHOOI9KCQBCRDIWJ9YRWLHIJJMVRAY9VAHJYOAATYHRFMICKSIPVHLFRSGVGIWAJMUEUVYYV' +
                        'WITTVZPYKVTVLNIXCPRSFURPHWYHUCWGGMDPDQWCQJSBPBHWQVZNLBQUHDDTNVPPRPMSQKXQPIDQUF9SC' +
                        'VAYEQDGPQUVIYEOWIXATHYHJTOSQACGSGTHVYOXKWZ9YRWTYTJXPLIOTUWRZARSVVHYQQIGDYWERZXGXK' +
                        'RPQIKSODGHKEPIZDACHPRPGXHXAZOAMBFYCRHLMWIIBQLJQEMJXLRMIPCDNJRMJGMMOGBIOOIBVLFUPYT' +
                        'VEXRTYGJZBQHPJGIMCOUBANBVNMBQ9CWDJHGQNI9VNTJSBEVMFJMFOZBCFZKQDIHGZYQCETPYGHNUYAYX' +
                        'VWMXHVOKKZBCVZTLWZKFDNEREJMHSNWITMAK9MQTQNZQKFALHQDQKSSFJOZSBXHEIIIJZNASEJGSNJNMR' +
                        'PHGCQISQHH9REONLGQTASNQLH9TOMGRNWPDVQIZGQZBRAGWNOJW9VENZW9OMBUUYKSKGBVRZ9AZAPIJFZ' +
                        'WEODMQFLSRCERSWCDWBJFTONVUAZMXUCARUWETEUDJIBLVKKBBIUFGWQUMM9OXTTWMPZZPFKPJDPTYPKT' +
                        'WFNAABXLYZJIKBQVHL9NPORO9TLJQABI9XPLQHVSDTZQCPURIPGSPIAFETQIHHEXBRSLXDIYIMEGTUVDS' +
                        'UVKZ9MXAWJNMQPZRCZV9OL9GIKPCYWYLUMAIMRJZILULMYRTFURGRBCUVTRTODANEJINQAPLNKFUDSPBA' +
                        'T9QDEVJPCZMHQZTYDRYA9AIETUN9JDOYJZGZMOONR9WAEXWHEO9AMENRKWEWIDNBMTMYWFUZBQXMTMLC9' +
                        'DNS9FQG9ZPL9HH9TLBPOGDBZCHXVXNNWNHBNZJWNVIYHFSCBDWVE9KJHZMPHT9HBQEIGVOPPQAFQZDVLW' +
                        'KALLHEXOZAFHPQPXIXZUIHBRD9FWIYRZ9BXMWNZQWOB9RENQJNGJYHRQCUPNETKBPHVPLNMVMLOOHFXFU' +
                        'WOFBPSKYV9ZCDEIUOOWFNCSRDZP99WYQHSODFQXOPZ9XMROIUGPBRUJOBGMFRXJSNHAKSCFFOB9OVD9BU' +
                        'KEOLYVRVKZPBUKCBFCX9ROWIKDAYZQZDRPRQPE9FTWWVPEZXE9CITNR9WOGXAZJKP9AQHWKKSZGLYFGCZ' +
                        'FGPTYY9MCCXEYWYEXBWADKR9V9VMPGTIGWSZMP9WBQQPSUVLRA9TCYYYCIFJLX9OXZGZCXMKPRDGGFQMI' +
                        'TAJJLZBTMBZXZPXPEXGNWEUXBOMWNJZRMNODDTNICUDTCNJUCYVSDDPIGKQZAWVATWNLZPIZUFEYUIVPZ' +
                        'ZWDGCTZCVE9YJAEIYTDWY9HCONHSILZUXWQKRHOGVFHDLLURLDNSKDTBVYXJOAAFZYMHECNIZUAWPBZUX' +
                        'RSXCWMMJXZBFVHBCYNMVVUJHZANICNSEWLRANHALZCZINVKJG9YORFJDRPTLRTJ9PQHNQDKSBNBLSONTU' +
                        '9PKFRMUCCJCT9LOTOKLLFPSMRGSZGHVLA9LSDBVIHLWNPVSOFBRH9PHHHOIXVXQCMQDELUICCAJZCPTCM' +
                        'KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU' +
                        '999999999999999999999999999FFH999999999999999999999999BMZEDVD99999999999A99999999' +
                        'RADCCDMEKWYHQLFYVLTTFMDCACBQNKAUGGUX9YUXBLOIJRSEIHJZUWESSEBCHAYOYFZORQAHHGXDVDCKK' +
                        'SJTDXDHHBY9LXEFNLURWLXYGZMAUWBRVOFFGEOEFZIVGIEWASDUHVVQPC9FLSQWCSWLRTYMRLMW999999' +
                        'ESVEN9ZFGRXQXPMXEKCEKFOEEENYQZONGHWQFY9WZABKMULSKL9DZTAMQEAFUMNMPDIDCAUAZPC999999' +
                        'WKR9ZVSILWCAHMBOBKDCFVMYVGRBJDNTAPEFFTFZIVHOUEIGQKADMXBVROKF9JFBZFHTDMRZUBFBJWAMR' +
                        ' OYHIBAJHIPIMSWTARLZMUDEOMCLUGDVIHSMTZKTLLKJDCOKDTLTQRI9YWNQLDDDXOBUUMQOFISA999999')

address_correct = [
    'KPWCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU'
]

address_wrong = [
    '99WCHICGJZXKE9GSUDXZYUAPLHAKAHYHDXNPHENTERYMMBQOPSQIDENXKLKCEYCPVTZQLEEJVYJZV9BWU'
]

branch_correct = [
    'ESVEN9ZFGRXQXPMXEKCEKFOEEENYQZONGHWQFY9WZABKMULSKL9DZTAMQEAFUMNMPDIDCAUAZPC999999'
]

branch_wrong = [
    '99VEN9ZFGRXQXPMXEKCEKFOEEENYQZONGHWQFY9WZABKMULSKL9DZTAMQEAFUMNMPDIDCAUAZPC999999'
]

signature_correct = [
    ('IHWBOXGKKUZDSSMVJKXGEQDSNWREWQROJFWFPFIGHDSRHOZTDBYZPAQQDQCIASONKDWMULCHMYWKDLGPA' +
     'MFVIPRIWOUWCAYGPWOCI9QKGQNDJVNGGWGQSLIFJGJOKIZPUAXPINEYYHCVSSBFQPPQLWXBCCSPWWHVER' +
     'TDALI9UNPZGIY9DD9VEDIABNLAJZZJPXERSISFGGHOUAQCKUBOJPRCOVPVXJJOGGWBOAZLI9QH9B9NYLK' +
     'XITTBH9MQMFZYZUZFKGC9VQKN9KA9XDQZMBABOT9ARLMIXQHWARWMB9UIDRYRC9SSKYEYUNX9SGDSNXTA' +
     '9LDJOWZUVKBYYBPUGSMIONX9LFNOKYDVEMNCAGCOGNOTUNZKSPOUVPHLGIMQMQGIUPIBGLVERWWGMINIT' +
     'AYVWLKMPVMZ9B9HNXAW9ZP9UWCRNQOLSPKMYZJVLRHQVNVFHFVIQFOY9UBYMRLLEKAGITQNJIZNFYDY9O' +
     'PJYHFJHCRUTEWXZUQEHLUSYPHXIGL9YPRXIUTGCD9JUAJUZ9TX9XPTWCDO9ULRJ9DXENRFLWCSAZJDDFM' +
     'FFHGQCQZGIHOOI9KCQBCRDIWJ9YRWLHIJJMVRAY9VAHJYOAATYHRFMICKSIPVHLFRSGVGIWAJMUEUVYYV' +
     'WITTVZPYKVTVLNIXCPRSFURPHWYHUCWGGMDPDQWCQJSBPBHWQVZNLBQUHDDTNVPPRPMSQKXQPIDQUF9SC' +
     'VAYEQDGPQUVIYEOWIXATHYHJTOSQACGSGTHVYOXKWZ9YRWTYTJXPLIOTUWRZARSVVHYQQIGDYWERZXGXK' +
     'RPQIKSODGHKEPIZDACHPRPGXHXAZOAMBFYCRHLMWIIBQLJQEMJXLRMIPCDNJRMJGMMOGBIOOIBVLFUPYT' +
     'VEXRTYGJZBQHPJGIMCOUBANBVNMBQ9CWDJHGQNI9VNTJSBEVMFJMFOZBCFZKQDIHGZYQCETPYGHNUYAYX' +
     'VWMXHVOKKZBCVZTLWZKFDNEREJMHSNWITMAK9MQTQNZQKFALHQDQKSSFJOZSBXHEIIIJZNASEJGSNJNMR' +
     'PHGCQISQHH9REONLGQTASNQLH9TOMGRNWPDVQIZGQZBRAGWNOJW9VENZW9OMBUUYKSKGBVRZ9AZAPIJFZ' +
     'WEODMQFLSRCERSWCDWBJFTONVUAZMXUCARUWETEUDJIBLVKKBBIUFGWQUMM9OXTTWMPZZPFKPJDPTYPKT' +
     'WFNAABXLYZJIKBQVHL9NPORO9TLJQABI9XPLQHVSDTZQCPURIPGSPIAFETQIHHEXBRSLXDIYIMEGTUVDS' +
     'UVKZ9MXAWJNMQPZRCZV9OL9GIKPCYWYLUMAIMRJZILULMYRTFURGRBCUVTRTODANEJINQAPLNKFUDSPBA' +
     'T9QDEVJPCZMHQZTYDRYA9AIETUN9JDOYJZGZMOONR9WAEXWHEO9AMENRKWEWIDNBMTMYWFUZBQXMTMLC9' +
     'DNS9FQG9ZPL9HH9TLBPOGDBZCHXVXNNWNHBNZJWNVIYHFSCBDWVE9KJHZMPHT9HBQEIGVOPPQAFQZDVLW' +
     'KALLHEXOZAFHPQPXIXZUIHBRD9FWIYRZ9BXMWNZQWOB9RENQJNGJYHRQCUPNETKBPHVPLNMVMLOOHFXFU' +
     'WOFBPSKYV9ZCDEIUOOWFNCSRDZP99WYQHSODFQXOPZ9XMROIUGPBRUJOBGMFRXJSNHAKSCFFOB9OVD9BU' +
     'KEOLYVRVKZPBUKCBFCX9ROWIKDAYZQZDRPRQPE9FTWWVPEZXE9CITNR9WOGXAZJKP9AQHWKKSZGLYFGCZ' +
     'FGPTYY9MCCXEYWYEXBWADKR9V9VMPGTIGWSZMP9WBQQPSUVLRA9TCYYYCIFJLX9OXZGZCXMKPRDGGFQMI' +
     'TAJJLZBTMBZXZPXPEXGNWEUXBOMWNJZRMNODDTNICUDTCNJUCYVSDDPIGKQZAWVATWNLZPIZUFEYUIVPZ' +
     'ZWDGCTZCVE9YJAEIYTDWY9HCONHSILZUXWQKRHOGVFHDLLURLDNSKDTBVYXJOAAFZYMHECNIZUAWPBZUX' +
     'RSXCWMMJXZBFVHBCYNMVVUJHZANICNSEWLRANHALZCZINVKJG9YORFJDRPTLRTJ9PQHNQDKSBNBLSONTU' +
     '9PKFRMUCCJCT9LOTOKLLFPSMRGSZGHVLA9LSDBVIHLWNPVSOFBRH9PHHHOIXVXQCMQDELUICCAJZCPTCM')
]

signature_wrong = [
    ('999BOXGKKUZDSSMVJKXGEQDSNWREWQROJFWFPFIGHDSRHOZTDBYZPAQQDQCIASONKDWMULCHMYWKDLGPA' +
     'MFVIPRIWOUWCAYGPWOCI9QKGQNDJVNGGWGQSLIFJGJOKIZPUAXPINEYYHCVSSBFQPPQLWXBCCSPWWHVER' +
     'TDALI9UNPZGIY9DD9VEDIABNLAJZZJPXERSISFGGHOUAQCKUBOJPRCOVPVXJJOGGWBOAZLI9QH9B9NYLK' +
     'XITTBH9MQMFZYZUZFKGC9VQKN9KA9XDQZMBABOT9ARLMIXQHWARWMB9UIDRYRC9SSKYEYUNX9SGDSNXTA' +
     '9LDJOWZUVKBYYBPUGSMIONX9LFNOKYDVEMNCAGCOGNOTUNZKSPOUVPHLGIMQMQGIUPIBGLVERWWGMINIT' +
     'AYVWLKMPVMZ9B9HNXAW9ZP9UWCRNQOLSPKMYZJVLRHQVNVFHFVIQFOY9UBYMRLLEKAGITQNJIZNFYDY9O' +
     'PJYHFJHCRUTEWXZUQEHLUSYPHXIGL9YPRXIUTGCD9JUAJUZ9TX9XPTWCDO9ULRJ9DXENRFLWCSAZJDDFM' +
     'FFHGQCQZGIHOOI9KCQBCRDIWJ9YRWLHIJJMVRAY9VAHJYOAATYHRFMICKSIPVHLFRSGVGIWAJMUEUVYYV' +
     'WITTVZPYKVTVLNIXCPRSFURPHWYHUCWGGMDPDQWCQJSBPBHWQVZNLBQUHDDTNVPPRPMSQKXQPIDQUF9SC' +
     'VAYEQDGPQUVIYEOWIXATHYHJTOSQACGSGTHVYOXKWZ9YRWTYTJXPLIOTUWRZARSVVHYQQIGDYWERZXGXK' +
     'RPQIKSODGHKEPIZDACHPRPGXHXAZOAMBFYCRHLMWIIBQLJQEMJXLRMIPCDNJRMJGMMOGBIOOIBVLFUPYT' +
     'VEXRTYGJZBQHPJGIMCOUBANBVNMBQ9CWDJHGQNI9VNTJSBEVMFJMFOZBCFZKQDIHGZYQCETPYGHNUYAYX' +
     'VWMXHVOKKZBCVZTLWZKFDNEREJMHSNWITMAK9MQTQNZQKFALHQDQKSSFJOZSBXHEIIIJZNASEJGSNJNMR' +
     'PHGCQISQHH9REONLGQTASNQLH9TOMGRNWPDVQIZGQZBRAGWNOJW9VENZW9OMBUUYKSKGBVRZ9AZAPIJFZ' +
     'WEODMQFLSRCERSWCDWBJFTONVUAZMXUCARUWETEUDJIBLVKKBBIUFGWQUMM9OXTTWMPZZPFKPJDPTYPKT' +
     'WFNAABXLYZJIKBQVHL9NPORO9TLJQABI9XPLQHVSDTZQCPURIPGSPIAFETQIHHEXBRSLXDIYIMEGTUVDS' +
     'UVKZ9MXAWJNMQPZRCZV9OL9GIKPCYWYLUMAIMRJZILULMYRTFURGRBCUVTRTODANEJINQAPLNKFUDSPBA' +
     'T9QDEVJPCZMHQZTYDRYA9AIETUN9JDOYJZGZMOONR9WAEXWHEO9AMENRKWEWIDNBMTMYWFUZBQXMTMLC9' +
     'DNS9FQG9ZPL9HH9TLBPOGDBZCHXVXNNWNHBNZJWNVIYHFSCBDWVE9KJHZMPHT9HBQEIGVOPPQAFQZDVLW' +
     'KALLHEXOZAFHPQPXIXZUIHBRD9FWIYRZ9BXMWNZQWOB9RENQJNGJYHRQCUPNETKBPHVPLNMVMLOOHFXFU' +
     'WOFBPSKYV9ZCDEIUOOWFNCSRDZP99WYQHSODFQXOPZ9XMROIUGPBRUJOBGMFRXJSNHAKSCFFOB9OVD9BU' +
     'KEOLYVRVKZPBUKCBFCX9ROWIKDAYZQZDRPRQPE9FTWWVPEZXE9CITNR9WOGXAZJKP9AQHWKKSZGLYFGCZ' +
     'FGPTYY9MCCXEYWYEXBWADKR9V9VMPGTIGWSZMP9WBQQPSUVLRA9TCYYYCIFJLX9OXZGZCXMKPRDGGFQMI' +
     'TAJJLZBTMBZXZPXPEXGNWEUXBOMWNJZRMNODDTNICUDTCNJUCYVSDDPIGKQZAWVATWNLZPIZUFEYUIVPZ' +
     'ZWDGCTZCVE9YJAEIYTDWY9HCONHSILZUXWQKRHOGVFHDLLURLDNSKDTBVYXJOAAFZYMHECNIZUAWPBZUX' +
     'RSXCWMMJXZBFVHBCYNMVVUJHZANICNSEWLRANHALZCZINVKJG9YORFJDRPTLRTJ9PQHNQDKSBNBLSONTU' +
     '9PKFRMUCCJCT9LOTOKLLFPSMRGSZGHVLA9LSDBVIHLWNPVSOFBRH9PHHHOIXVXQCMQDELUICCAJZCPTCM')
]

bundle_correct = [
    'RADCCDMEKWYHQLFYVLTTFMDCACBQNKAUGGUX9YUXBLOIJRSEIHJZUWESSEBCHAYOYFZORQAHHGXDVDCKK'
]

bundle_wrong = [
    '99DCCDMEKWYHQLFYVLTTFMDCACBQNKAUGGUX9YUXBLOIJRSEIHJZUWESSEBCHAYOYFZORQAHHGXDVDCKK'
]

nonce_correct = ['BVROKF9JFBZFHTDMRZUBFBJWAMR']

nonce_wrong = ['99ROKF9JFBZFHTDMRZUBFBJWAMR']

obsolete_tag_correct = ['FFH999999999999999999999999']

obsolete_tag_wrong = ['99H999999999999999999999999']

tag_correct = ['WKR9ZVSILWCAHMBOBKDCFVMYVGR']

tag_wrong = ['99R9ZVSILWCAHMBOBKDCFVMYVGR']

transaction_hash_correct = [
    'OYHIBAJHIPIMSWTARLZMUDEOMCLUGDVIHSMTZKTLLKJDCOKDTLTQRI9YWNQLDDDXOBUUMQOFISA999999'
]

transaction_hash_wrong = [
    '99HIBAJHIPIMSWTARLZMUDEOMCLUGDVIHSMTZKTLLKJDCOKDTLTQRI9YWNQLDDDXOBUUMQOFISA999999'
]

trunk_correct = [
    'SJTDXDHHBY9LXEFNLURWLXYGZMAUWBRVOFFGEOEFZIVGIEWASDUHVVQPC9FLSQWCSWLRTYMRLMW999999'
]

trunk_wrong = [
    '99TDXDHHBY9LXEFNLURWLXYGZMAUWBRVOFFGEOEFZIVGIEWASDUHVVQPC9FLSQWCSWLRTYMRLMW999999'
]
