
MILESTONES_USING_TIMESTAMP_ONLY: set([str]) = set(
    ['6000', '13157', '18675', '61491', '150354', '216223', '242662', '337541'])
"""
For the transactions with milestones in MILESTONES_USING_TIMESTAMP_ONLY, the timestamp is used directly.
For other transactions, the attachmentTimestamp will be used if it is not zero, else timestamp is used.
"""
TRANSACTION_HASH_LENGTH = 81
ZMQ_TRYTES_TOPIC_OFFSET = 7
OFFSET = [2187, 81, 27, 27, 9, 9, 9, 81, 81, 81, 27, 9, 9, 9, 27]
SIGNATURE_B = 0
SIGNATURE_E = SIGNATURE_B + OFFSET[0]
ADDRESS_B = SIGNATURE_E
ADDRESS_E = ADDRESS_B + OFFSET[1]
VALUE_B = ADDRESS_E
VALUE_E = VALUE_B + OFFSET[2]
OBSOLETE_TAG_B = VALUE_E
OBSOLETE_TAG_E = OBSOLETE_TAG_B + OFFSET[3]
TIMESTAMP_B = OBSOLETE_TAG_E
TIMESTAMP_E = TIMESTAMP_B + OFFSET[4]
CURRENT_IDX_B = TIMESTAMP_E
CURRENT_IDX_E = CURRENT_IDX_B + OFFSET[5]
LAST_IDX_B = CURRENT_IDX_E
LAST_IDX_E = LAST_IDX_B + OFFSET[6]
BUNDLE_HASH_B = LAST_IDX_E
BUNDLE_HASH_E = BUNDLE_HASH_B + OFFSET[7]
TRUNK_B = BUNDLE_HASH_E
TRUNK_E = TRUNK_B + OFFSET[8]
BRANCH_B = TRUNK_E
BRANCH_E = BRANCH_B + OFFSET[9]
TAG_B = BRANCH_E
TAG_E = TAG_B + OFFSET[10]
ATCH_TIMESTAMP_B = TAG_E
ATCH_TIMESTAMP_E = ATCH_TIMESTAMP_B + OFFSET[11]
ATCH_TIMESTAMP_LOWER_B = ATCH_TIMESTAMP_E
ATCH_TIMESTAMP_LOWER_E = ATCH_TIMESTAMP_LOWER_B + OFFSET[12]
ATCH_TIMESTAMP_UPPER_B = ATCH_TIMESTAMP_LOWER_E
ATCH_TIMESTAMP_UPPER_E = ATCH_TIMESTAMP_UPPER_B + OFFSET[13]
NONCE_B = ATCH_TIMESTAMP_UPPER_E
NONCE_E = NONCE_B + OFFSET[14]
"""
The offset of each field in trytes
"""
